CLOUDERA-BUILD: CDH-46335 - netty fixes
CLOUDERA-BUILD: excluding Netty from two POMs, add missing property to LauncherMapperHelper
CLOUDERA-BUILD fix Jetty version (3.10.5.Final is necessary to avoid NoSuchMethodError in HttpResponse)

Change-Id: I2a060f8f65511a66af127b9d64876420fc83285e